#cloud-config

hostname: coreos1
users: 
  - name: kuroishi
    coreos-ssh-import-github: dkoppel
    groups:
        - sudo
        - docker
  - name: dockerbot
    coreos-ssh-import-github: dkoppel
    groups:
        - sudo
        - docker
units:
  - name: docker-tcp.socket
    command: start
    enable: yes
    content: |
      [Unit]
      Description=Docker Socket for the API

      [Socket]
      ListenStream=2375
      BindIPv6Only=both
      Service=docker.service

      [Install]
      WantedBy=sockets.target
  - name: enable-docker-tcp.service
    command: start
    content: |
      [Unit]
      Description=Enable the Docker Socket for the API

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/systemctl enable docker-tcp.socket
